const initialReportsQuery = { query: 
    `query {
        reports{
            totalReports
            reports{
                    _id
                reportDate
                shift
                createdAt
                updatedAt
                userId{
                    name
                }
                machine{
                    _id
                    machineNumber
                    machineSerial
                }
                TReal
                TNG
                TOK
                TPlan
                TProd
                TWTime
                TDTime
                TAvailability
                TPerformance
                TQuality
                TOEE
                production{
                    _id
                    program{
                        _id
                    }
                    real
                    ng
                    ok
                    plan
                    prod
                    wtime
                    dtime
                    availability
                    performance
                    quality
                    oee
                    partNumber {
                        _id
                        partNumber
                        partName
                        family
                    }
                    molde{
                        _id
                        moldeNumber
                        moldeSerial
                        cavities
                    }
                }
                downtimeDetail {
                    _id
                    issueId{
                        _id
                        issueName
                    }
                    mins
                }
                resines {
                    _id
                    resine{
                        _id
                    description
                    }
                    purge
                }
                defects{
                    _id
                    defect{
                        _id
                        defectName
                        defectCode
                    }
                    defectPcs
                    molde{
                        _id
                        moldeNumber
                    }
                    partNumber{
                        _id
                        partNumber
                        partName
                        family
                    }
                    program{
                        _id
                    }
                }
                comments
                workers{
                    team
                    inspector
                    operator
                }
            }   
        }
    }`
};

const reportsQuery = { query: `query 
    Reports( $page: Int, $add: Int ){
        reports( page:$page, add:$add ){
            totalReports
            reports{
                    _id
                reportDate
                shift
                createdAt
                updatedAt
                userId{
                    name
                }
                machine{
                    _id
                    machineNumber
                    machineSerial
                }
                TReal
                TNG
                TOK
                TPlan
                TProd
                TWTime
                TDTime
                TAvailability
                TPerformance
                TQuality
                TOEE
                production{
                    _id
                    program{
                        _id
                    }
                    real
                    ng
                    ok
                    plan
                    prod
                    wtime
                    dtime
                    availability
                    performance
                    quality
                    oee
                    partNumber {
                        _id
                        partNumber
                        partName
                        family
                    }
                    molde{
                        _id
                        moldeNumber
                        moldeSerial
                        cavities
                    }
                }
                downtimeDetail {
                    _id
                    issueId{
                        _id
                        issueName
                    }
                    mins
                }
                resines {
                    _id
                    resine{
                        _id
                    description
                    }
                    purge
                }
                defects{
                    _id
                    defect{
                        _id
                        defectName
                        defectCode
                    }
                    defectPcs
                    molde{
                        _id
                        moldeNumber
                    }
                    partNumber{
                        _id
                        partNumber
                        partName
                        family
                    }
                    program{
                        _id
                    }
                }
            }
        }
    }`,
};

const workersQuery = { query: `query 
    Workers( $inspectorId: ID, $operatorId: ID ){
        workers(inspectorId: $inspectorId, operatorId: $operatorId){
            operator{
                _id
                firstname
                lastname
            }
            inspector{
                _id
                firstname
                lastname
            }
        }
    }`,
};

export { reportsQuery, initialReportsQuery, workersQuery}